### Creating Table with Full Text enabled

In [ ]:
%%sql
CREATE TABLE articles (
        id INT,
        year INT,
        title VARCHAR(200),
        body TEXT,
        SORT KEY (id),
        FULLTEXT USING VERSION 2 art_ft_index (title, body));

### Inserting Sample Full Text Data

In [ ]:
%%sql
INSERT INTO articles (id, year, title, body) VALUES 
    (1, 2021, 'Introduction to SQL', 'SQL is a standard language for accessing and manipulating databases.'),
    (2, 2022, 'Advanced SQL Techniques', 'Explore advanced techniques and functions in SQL for better data manipulation.'),
    (3, 2020, 'Database Optimization', 'Learn about various optimization techniques to improve database performance.'),
    (4, 2023, 'SQL in Web Development', 'Discover how SQL is used in web development to interact with databases.'),
    (5, 2019, 'Data Security in SQL', 'An overview of best practices for securing data in SQL databases.'),
    (6, 2021, 'NoSQL vs SQL', 'A comprehensive comparison between NoSQL and SQL databases.'),
    (7, 2022, 'SQL Injection Prevention', 'Understanding SQL injection and how to protect against it.'),
    (8, 2020, 'Building Data Models', 'Learn how to design effective data models for SQL databases.'),
    (9, 2023, 'SQL and Big Data', 'Explore the role of SQL in handling big data applications.'),
    (10, 2018, 'Introduction to Relational Databases', 'An overview of relational databases and their fundamentals.'),
    (11, 2021, 'Dynamic SQL', 'Using dynamic SQL to build flexible and powerful queries.'),
    (12, 2022, 'SQL Performance Tuning', 'Tips and techniques for tuning SQL queries for better performance.'),
    (13, 2019, 'Stored Procedures in SQL', 'Learn how to create and use stored procedures effectively.'),
    (14, 2020, 'Using Triggers in SQL', 'Understanding how and when to use triggers in SQL databases.'),
    (15, 2023, 'SQL and Cloud Databases', 'An introduction to using SQL with cloud-based database solutions.'),
    (16, 2017, 'Introduction to PostgreSQL', 'A beginnerâ€™s guide to PostgreSQL and its features.'),
    (17, 2019, 'MySQL for Beginners', 'Learn the basics of MySQL, one of the most popular SQL databases.'),
    (18, 2021, 'Working with Indexes', 'How to use indexes effectively to optimize query performance.'),
    (19, 2022, 'Partitioning in SQL', 'Learn about table partitioning for managing large datasets.'),
    (20, 2020, 'SQL Joins Explained', 'An in-depth guide to SQL joins and their applications.'),
    (21, 2023, 'Role of SQL in Data Science', 'Discover how SQL is used in data science and analytics.'),
    (22, 2018, 'Backup and Recovery in SQL', 'Best practices for SQL database backup and recovery.'),
    (23, 2022, 'SQL for Data Visualization', 'Using SQL to prepare data for visualization tools.'),
    (24, 2020, 'Normalization in SQL', 'Learn the principles and practices of database normalization.'),
    (25, 2023, 'Emerging Trends in SQL', 'A look at the latest trends and developments in SQL technology.'),
    (26, 2021, 'SQL for Beginners', 'An introduction to SQL for those new to databases.'),
    (27, 2019, 'Handling NULL Values', 'Understanding and managing NULL values in SQL queries.'),
    (28, 2022, 'Common Table Expressions', 'Learn about CTEs and how to use them for complex queries.'),
    (29, 2020, 'Transactions in SQL', 'An overview of SQL transactions and their properties.'),
    (30, 2023, 'AI Integration with SQL', 'How SQL is evolving to integrate with artificial intelligence systems.');

In [ ]:
%%sql
OPTIMIZE TABLE articles FLUSH;

### Exact Match Full Text Search

In [ ]:
%%sql
SELECT *
FROM articles
WHERE MATCH (TABLE articles) AGAINST ("body:understanding");

### Exact Match with Filters Full Text Search

In [ ]:
%%sql
SELECT *
FROM articles
WHERE MATCH (TABLE articles)
AGAINST ('title:database OR body:database');

In [ ]:
%%sql
SELECT *
FROM articles
WHERE MATCH (TABLE articles)
AGAINST ('title:database AND body:database');

### Wildcard Match Full Text Search

In [ ]:
%%sql
SELECT id, title
FROM articles
WHERE MATCH(TABLE articles) AGAINST ('title:Intro*');

### Relevance Match Full Text Search

In [ ]:
%%sql
SELECT id, title, MATCH(TABLE articles) AGAINST ('body:database') AS relevance
FROM articles
WHERE MATCH(TABLE articles) AGAINST('body:database')
order by relevance desc;